### ISSUE TITLE
Complete Inventory 

### ISSUE THREAD

**Issue by lsharma13** [AryaTwohey/Zork---Arya-Lara-Arman-Muriel#3]

**Comment by AryaTwohey** [comment]
Wrote the removeItem method, but im not sure if one line of code works, 

 The only thing im questioning is if the item.getName needs to know where the index of i is in order to get the actual name and see if it matches up with the useranswer, any ideas on how to do this, I have already tried passing in i, but the arraylist takes type  ITEM, so that wont work                 

______________________________________________________________________________________
 **for(int i = 0; i < items.size(); i++){
          if(useranswer.equals(item.getName())){      //not sure if this will work 
            items.remove(i);
            return true;
          }
      }**
